---
# tasks file for common
  - name: Set timezone to Asia/Bangkok
    timezone:
      name: Asia/Bangkok

  - name: Install remi repo.
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present

  - name: Import remi GPG key.
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present
  
  - name: Enable service Firewall
    service:
      name: firewalld
      enabled: yes

  - name: Start firewalld Service
    service: 
      name: firewalld 
      state: started

  - name: copy config rsyslog 
    template:
      src: 'templates/rsyslog.conf.j2'
      dest: '/etc/rsyslog.conf'
      owner: root
      group: root
      mode: "0644"
    notify: restart rsyslog  